CREATE TABLE CLIENTE(
	ID_CLIENTE INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(70) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	EMAIL VARCHAR(60),
	NUMCELULAR VARCHAR(15),
	HOST VARCHAR(50)	
);